// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Data;

#nullable disable

namespace Notification.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110052755_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notification.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 11, 5, 5, 27, 55, 93, DateTimeKind.Utc).AddTicks(4386),
                            CreatedBy = "system.admin@example.com",
                            Description = "Finish the API documentation for the notification system with detailed examples",
                            IsDeleted = false,
                            Title = "Complete Project Documentation",
                            UpdatedAt = new DateTime(2025, 11, 8, 5, 27, 55, 93, DateTimeKind.Utc).AddTicks(4392),
                            UpdatedBy = "documentation.team@example.com"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            CreatedAt = new DateTime(2025, 11, 7, 5, 27, 55, 93, DateTimeKind.Utc).AddTicks(4399),
                            CreatedBy = "developer@example.com",
                            Description = "Create real-time notification hub for client connections with authentication",
                            IsDeleted = false,
                            Title = "Implement SignalR Hub",
                            UpdatedAt = new DateTime(2025, 11, 9, 5, 27, 55, 93, DateTimeKind.Utc).AddTicks(4400),
                            UpdatedBy = "senior.developer@example.com"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            CreatedAt = new DateTime(2025, 11, 9, 5, 27, 55, 93, DateTimeKind.Utc).AddTicks(4402),
                            CreatedBy = "tester@example.com",
                            Description = "Write comprehensive unit tests for the notification service layer including edge cases",
                            IsDeleted = false,
                            Title = "Test Notification Service"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-def4-456789012345"),
                            CreatedAt = new DateTime(2025, 11, 9, 17, 27, 55, 93, DateTimeKind.Utc).AddTicks(4404),
                            CreatedBy = "dba@example.com",
                            Description = "Configure EF Core migrations and database seeding with proper relationships",
                            IsDeleted = false,
                            Title = "Setup Database Migrations"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            CreatedAt = new DateTime(2025, 11, 9, 23, 27, 55, 93, DateTimeKind.Utc).AddTicks(4405),
                            CreatedBy = "devops@example.com",
                            Description = "Deploy the application to development environment for testing and validation",
                            IsDeleted = false,
                            Title = "Deploy to Development Server"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-f678-901234567890"),
                            CreatedAt = new DateTime(2025, 11, 10, 2, 27, 55, 93, DateTimeKind.Utc).AddTicks(4409),
                            CreatedBy = "tech.lead@example.com",
                            Description = "Conduct peer code review for the latest feature implementations",
                            IsDeleted = false,
                            Title = "Code Review Session"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-7890-123456789012"),
                            CreatedAt = new DateTime(2025, 11, 10, 4, 27, 55, 93, DateTimeKind.Utc).AddTicks(4411),
                            CreatedBy = "performance.team@example.com",
                            Description = "Optimize database queries and API response times",
                            IsDeleted = false,
                            Title = "Performance Optimization"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
